### ISSUE TITLE
Settle on a CMS

### ISSUE THREAD

**Issue by mray** [freedombox/freedombox.org#5]
We need to run this page with some kind of CMS I guess. We *could* use plain html, but i think that is a recipe to make sure nobody wants to maintain it.

My suggestion would be [Jekyll](https://jekyllrb.com/) as a static site generator, but I'm aware that the translation capabilites are very.

@SunilMohanAdapa any results from your side in that question?

**Comment by phylophyl** [comment]
If we need static pages and the use of po files, the first solution would be to host a gitlab and publish pages for that.

**Comment by mray** [comment]
Well I hope we don't go for stonage tools for publishing and high-tech tools for translation.

**Comment by phylophyl** [comment]
please see https://pages.gitlab.io/ for cutting edge process 

there is also for gettext integration
https://www.getlektor.com/
+
https://github.com/numericube/lektor-i18n-plugin

**Comment by phylophyl** [comment]
**Adva Cms** (seems dead regarding dev activity)
http://adva-cms.org/wiki
https://github.com/svenfuchs/adva_cms
"adva cms was build with Internationalization in mind right from the start and will use Rails 2.2’s I18n API and Globalize2 to enable multilanguage sites transparently."

**Comment by phylophyl** [comment]
static site generator directory
https://www.staticgen.com/

**Comment by phylophyl** [comment]
Popular static site convertor Pelican "Publish content in multiple languages"
http://blog.getpelican.com/

**Comment by petterreinholdtsen** [comment]
[mray]
> We need to run this page with some kind of CMS I guess. We *could* use
> plain html, but i think that is a recipe to make sure nobody wants to
> maintain it. 

What about using markdown or similar to edit the text and generate the
web pages from this?  It would be trivial to handle translations as PO
files using po4a, and we could keep everything in git and use weblate
for translations.

See https://github.com/samaaron/sonic-pi/pull/870 for a patch I made for
sonic-pi (which already used markdown) to make the documentation
translatable using po4a and PO files.

--
Happy hacking
Petter Reinholdtsen

**Comment by mray** [comment]
I'm a fan of things that work out of the box more or less. I don't like to mess around because I lack the skills, and there is the risk of suddenly being dependent on the creator of some highly customized solution.

My way would be to try sticking with the most commonly used static site genrator that also allows for translations relatively easy. But it is up to @SunilMohanAdapa or somebody else who has then to take care of it all I guess.

**Comment by phylophyl** [comment]
These static site convertors requiere a learning curve yes, and i know what you mean as an editor, although Letktor allows 3 development levels (gitlab/github direct editing, lektor automation process for gettext/po files, and editing from online pages). 

adva cms is pretty straight forward. you can see admin interface
https://duckduckgo.com/?q=adva+cms&t=ffsb&iax=1&ia=images&iai=http%3A%2F%2Fadva-cms.org%2Fimages%2Fadva-cms-screen_0-2-0_1.png

i guess we are all depending on that choice as designer, editor and developer. Like you, i won't interfer that much in technical tool final choice, i can focus on my value (content), i am trying to do the research to find something that can fit to your @mray and @SunilMohanAdapa needs : out of the box + static + po files. I can do the effort to learn Lektor or other convertors if it is usefull at a point because i have to use them professionally later.

@petterreinholdtsen do we really need a cms with your patch?

**Comment by petterreinholdtsen** [comment]
[Philippe Baret]
> @petterreinholdtsen do we really need a cms with your patch?

The idea I talked about just need a file format that po4a can understand
and makefile or a script to generate the HTML pages.
--
Happy hacking
Petter Reinholdtsen

**Comment by phylophyl** [comment]
middleman has a reputation for localization
https://middlemanapp.com/advanced/localization/

**Comment by SunilMohanAdapa** [comment]
Lektor seems to be a pretty good fit.  Let us start using it.  My reasoning follows:

* Supports markdown for parts of pages while uses templates for full power.
* Has an editing interface like CMS. No programming knowledge necessary.
* Setup is quite simple.
* Content is fully configurable.
* Translations are by exported to .POT files when using then lektor-i18n plugin.  This fits nicely with Transifex and Weblate.
* Simple file structure well suited to keep the project under Git and to deploy using static files.
* Has an inbuilt web server during development.
* Simple 5 minute video to get started.
* Programming language is Python - same as Plinth. Extending it, if the need arises, would be easy for current contributors.
* Template language is Jinja2 which is similar to Django templates used in Plinth.

Some additional notes about localization:
* For common content that is put in headers, footers etc. we will need to create a special page and model and lookup string from there.
* For alternatives configuration required in the project file, [alternative._primary] should be section name rather than [alternative.en].
* I have [fixed a couple of bugs](https://github.com/numericube/lektor-i18n-plugin/pull/1) in the lektor-i18n plugin. I recommend using [my repository](https://github.com/SunilMohanAdapa/lektor-i18n-plugin) until the fixes are merged. 

I have spent some time understanding the CMS and can help out with issues.  If i18n part is not straight forward, please leave that to me.

**Comment by SunilMohanAdapa** [comment]
My patches got merged.

Unless there are objections to the choice of Lektor as CMS, I believe we should close this issue.  I am also available if assistance is required for converting from current HTML pages to Lektor, or for creating a base project.

**Comment by phylophyl** [comment]
@SunilMohanAdapa
could you be more specific about these patches?

**Comment by SunilMohanAdapa** [comment]
> I have fixed a couple of bugs in the lektor-i18n plugin.

I submitted these fixes upstream and they got merged.

**Comment by jvalleroy** [comment]
We now have a (bare bones) Lektor project, so I think this can be closed.
